import test from 'node:test'
import assert from 'node:assert/strict'
import {createPriceState,processPriceBatch,predictPrice} from './priceModel.js'
import {priceFeature,estimateProbabilities,probabilityBucket,confidenceScore,riskStatus,confidenceLabel} from './priceCalibration.js'
const p={player_id:1,name:'Local unit test',club:'Test only',price:50,ownership:10,transfers_in:100,transfers_out:20,transfers_in_event:1,transfers_out_event:0,gameweek:1}
const at='2026-09-09T02:20:00Z',cycle={reset:p,previous:{...p,captured_at:at},confirmed:false,last_change:null,snapshot_count:1,max_gap_minutes:1440}
const record=(n,rise,fall,days=5)=>({n,rise,fall,days,evaluated:n,correct:n-2})
test('probability remains available without exact peer history, confidence is separate',()=>{const s=createPriceState('2026-2027');s.population=record(200,190,2);const f=priceFeature(p,cycle);const prob=estimateProbabilities(s,f);assert(prob.rise>90);assert.equal(prob.basis,'season');const pred=predictPrice(s,p,cycle,at,10000);assert(pred.rise_probability>90);assert(pred.confidence_score<50);assert.equal(pred.comparable_historical_hitrate,null);assert.notEqual(pred.status,'insufficient');assert.equal(pred.confidence_label,confidenceLabel(pred.confidence_score))})
test('small exact cohorts are pooled, tiny hitrates are withheld',()=>{const s=createPriceState('2026-2027'),f=priceFeature(p,cycle);s.population=record(400,60,20);s.bins[f.exact]=record(6,4,0,2);const pred=predictPrice(s,p,cycle,at,10000);assert(pred.rise_probability>15&&pred.rise_probability<67);assert.equal(pred.comparable_historical_count,6);assert.equal(pred.comparable_historical_hitrate,null);s.bins[f.exact]=record(26,20,1,5);const second=predictPrice(s,p,cycle,at,10000);assert.equal(second.comparable_historical_hitrate,92.31);assert.equal(second.comparable_historical_correct,24)})
test('only past bucket outcomes calibrate overconfident and conservative estimates',()=>{const s=createPriceState('2026-2027'),f=priceFeature(p,cycle);s.population=record(200,190,1,8);let before=estimateProbabilities(s,f);s.calibration={[`rise:${probabilityBucket(before.raw_rise)}`]:{n:100,actual:75,predicted_sum:before.raw_rise*100,days:5}};const after=estimateProbabilities(s,f);assert(after.rise<before.rise);assert(after.rise>75);s.calibration[`rise:${probabilityBucket(before.raw_rise)}`].actual=99;assert(estimateProbabilities(s,f).rise>before.rise)})
test('requested probability buckets and confidence independently determine labels',()=>{assert.deepEqual([50,59,60,89,90,94,95,99].map(probabilityBucket),['50–59','50–59','60–69','80–89','90–94','90–94','95–100','95–100']);assert.equal(riskStatus(96,87,91,'rise'),'very_likely');assert.equal(riskStatus(96,30,50,'rise'),'near');assert.equal(riskStatus(null,80,80,'rise'),'insufficient');assert.equal(riskStatus(82,65,95,'fall'),'likely')})
test('threshold dispersion produces transfer range, without requiring probability',()=>{const s=createPriceState('2026-2027');s.thresholds.rise=[50,80,100,120,180,200].map(value=>({value,group:2,confirmed:false}));const moved={...p,transfers_in:140};const pred=predictPrice(s,moved,cycle,at,10000);assert.deepEqual(pred.estimated_remaining_range,[40,140]);assert.equal(pred.estimated_remaining_net_transfers,80);assert(pred.threshold_confidence_score>0);assert.equal(pred.rise_probability,null)})
test('freshness, sample diversity, reset quality and gaps affect confidence, not raw probability',()=>{const estimate={rise:96,samples:500,days:12,basis:'comparable',calibration_error:3},threshold={spread:.1},base={estimate,cycle,at,threshold,ownership:10};const low=confidenceScore(base),high=confidenceScore({...base,cycle:{...cycle,confirmed:true,snapshot_count:50,max_gap_minutes:5}});assert(high>low);assert(high>=75);assert(confidenceScore({...base,at:'2026-09-09T04:20:00Z'})<low)})
test('rounded zero ownership cannot produce a false zero remaining sales estimate',()=>{const s=createPriceState('2026-2027');s.thresholds.fall=Array.from({length:8},()=>({value:.1,group:0,confirmed:false}));const zero={...cycle,reset:{...p,ownership:0}},pred=predictPrice(s,{...p,ownership:0,transfers_out:40},zero,at,10000);assert.equal(pred.estimated_remaining_net_transfers,null);assert.equal(pred.price_pressure_percentage,null)})
