import assert from 'node:assert/strict'
import { analyzeStructuralFixtureBlocks, findUpcomingGreenRunStart, scanUpcomingSwingPoints } from './structuralFixtureIntelligence.js'

const positive = analyzeStructuralFixtureBlocks({ previous:[40,45,50,55,50], next:[70,75,80,75,80], following:[70,70,70,70,70] })
assert.equal(positive.previousAverage,48); assert.equal(positive.nextAverage,76); assert.equal(positive.structuralSwing,28)
const negative = analyzeStructuralFixtureBlocks({ previous:[80,75,80,75,70], next:[45,50,40,45,50] })
assert.equal(negative.structuralSwing,-30)
const singleExtreme = analyzeStructuralFixtureBlocks({ previous:[50,50,50,50,50], next:[100,50,50,50,50] })
assert.equal(singleExtreme.structuralSwing,null, 'één extreme fixture maakt geen structureel verhaal')
assert.equal(analyzeStructuralFixtureBlocks({ previous:[40,50], next:[80,80,80,80,80] }).structuralSwing,null, 'previous sample onder drie')
const green = analyzeStructuralFixtureBlocks({ previous:[75,75,75,75,75], next:[82,82,82,82,82] })
assert.equal(green.structuralSwing,null); assert.equal(green.greenRun,true, 'Green Run bestaat zonder swing')
const cliff = analyzeStructuralFixtureBlocks({ previous:[70,70,70], next:[82,82,82,82,82], following:[48,48,48,48,48] })
assert.equal(cliff.scheduleCliff,true); assert.equal(cliff.scheduleCliffDelta,-34)
assert.equal(analyzeStructuralFixtureBlocks({ previous:[50,50,50], next:[45,75,80,78,76] }).greenRunStart,true, 'groene reeks start na eerste fixture')
const missing = analyzeStructuralFixtureBlocks({ previous:[50,null,undefined,50,50], next:[70,null,70,70,70] })
assert.equal(missing.previousScores.length,3); assert.equal(missing.nextScores.length,4); assert.equal(missing.structuralSwing,20)
assert.ok(Number.isFinite(missing.confidence.score)); assert.equal(analyzeStructuralFixtureBlocks({ previous:[], next:[] }).delta,null)
const positiveTimeline=[1,2,3,4,5].map(round=>({round,score:48})).concat([6,7,8,9,10].map(round=>({round,score:74})))
assert.equal(scanUpcomingSwingPoints(positiveTimeline,{currentRound:3})[0].startRound,6,'upcoming positive start op SR6')
assert.equal(scanUpcomingSwingPoints(positiveTimeline,{currentRound:3})[0].type,'positive')
const negativeTimeline=[1,2,3,4,5,6,7,8].map(round=>({round,score:80})).concat([9,10,11,12,13].map(round=>({round,score:55})))
assert.equal(scanUpcomingSwingPoints(negativeTimeline,{currentRound:3})[0].startRound,9,'upcoming negative start op SR9')
assert.equal(scanUpcomingSwingPoints([1,2,3,4,5].map(round=>({round,score:50})).concat([6,7,8,9,10].map(round=>({round,score:57}))),{currentRound:3}).length,0,'kleine swings blijven stil')
const clustered=scanUpcomingSwingPoints(positiveTimeline.concat([{round:11,score:74},{round:12,score:74}]),{currentRound:3})
assert.equal(clustered.filter(item=>item.type==='positive').length,1,'nabijgelegen punten worden geclusterd')
assert.equal(findUpcomingGreenRunStart([{round:3,score:45},...[4,5,6,7,8].map(round=>({round,score:78}))],{currentRound:3}).startRound,4)
const low=analyzeStructuralFixtureBlocks({previous:[],next:[]}).confidence.level, medium=analyzeStructuralFixtureBlocks({previous:[50,50,50],next:[50,50,50,50]}).confidence.level, high=positive.confidence.level
assert.deepEqual([low,medium,high],['laag','middel','hoog'],'confidence heeft bereik laag/middel/hoog')
console.log('Structural Fixture Intelligence: 21 controles geslaagd.')
