import assert from 'node:assert/strict'
import { buildTransferClubRows, canonicalTransferClub, createTransferDuplicateKey, enrichTransfers, getTransferCategory, getTransferFantasyData, mergeTransferRows, matchTransferPlayer, normalizeManualTransfer, normalizeTransferOwnership, normalizeTransferRow, sortTransferClubRanking, stepTransferClubIndex, validateWindowScore } from './transferDeadlineData.js'
import { logoSlug } from './clubIdentity.js'

const known={id:'p1',name:'Ángel Alarcón',club:'FC Utrecht',position:'aanvaller',endPrice:7.5,selectedPct:0.047,points:11,minutes:180}
const transfer=normalizeTransferRow({Club:'Utrecht',Richting:'IN',Speler:'Angel Alarcon',Van:'Porto',Naar:'FC Utrecht',Status:'Bevestigd'})
assert.equal(transfer.club,'FC Utrecht')
assert.equal(matchTransferPlayer(transfer,[known]).player.id,'p1')
const enriched=enrichTransfers([transfer],[known])[0]
assert.equal(enriched.matchStatus,'linked')
assert.equal(enriched.fantasyPrice,7.5)
assert.equal(enriched.ownership,4.7)
assert.equal(enriched.points,11)
assert.equal(enriched.minutes,180)
assert.equal(normalizeTransferOwnership('12,4%'),12.4)
assert.equal(getTransferFantasyData(known).fantasyPrice,7.5)
assert.equal(getTransferFantasyData(known).ownership,4.7)
assert.deepEqual(validateWindowScore(0),{valid:true,value:0})
assert.deepEqual(validateWindowScore(100),{valid:true,value:100})
assert.equal(validateWindowScore(72.5).valid,false)
assert.equal(validateWindowScore(101).valid,false)
const unknown=enrichTransfers([normalizeTransferRow({Club:'Ajax',Richting:'IN',Speler:'Onbekende Speler'})],[known])[0]
assert.equal(unknown.matchStatus,'unlinked')
assert.equal(unknown.fantasyPrice,null)
const clubs=buildTransferClubRows([enriched],[])
assert.equal(clubs.length,18)
assert.equal(clubs.find(row=>row.club==='FC Utrecht').inCount,1)
assert.equal(matchTransferPlayer(normalizeTransferRow({Club:'FC Twente',Richting:'IN',Speler:'Wout Weghorst'}),[{id:'p2',name:'Weghorst',club:'FC Twente'}]).player.id,'p2')
assert.equal(matchTransferPlayer(normalizeTransferRow({Club:'Ajax',Richting:'IN',Speler:'Jan Jansen'}),[{id:'a',name:'Jansen',club:'Ajax'},{id:'b',name:'Jansen',club:'Ajax'}]).status,'uncertain')
assert.equal(getTransferCategory({from:'Ajax',to:'PSV'}),'BINNEN EREDIVISIE')
assert.equal(getTransferCategory({from:'Arsenal',to:'Ajax'}),'NIEUW')
assert.equal(getTransferCategory({from:'Ajax',to:'Arsenal'}),'VERTROKKEN UIT EREDIVISIE')
assert.equal(getTransferCategory({from:'Ajax',to:'Nog niet bekend'}),'BESTEMMING ONBEKEND')
assert.equal(canonicalTransferClub('Cambuur'),'SC Cambuur')
assert.equal(canonicalTransferClub('Cambuur Leeuwarden'),'SC Cambuur')
assert.equal(canonicalTransferClub('SC Cambuur'),'SC Cambuur')
assert.equal(getTransferCategory({from:'SC Cambuur',to:'Ajax'}),'BINNEN EREDIVISIE')
assert.equal(logoSlug('SC Cambuur'),'cambuur-leeuwarden')
const manual=normalizeManualTransfer({playerName:'Nieuwe Speler',from:'Arsenal',to:'Ajax',type:'huur'})
assert.equal(manual.direction,'IN')
assert.equal(manual.localTransfer,true)
assert.equal(manual.category,'NIEUW')
const merged=mergeTransferRows([transfer],[manual,manual])
assert.equal(merged.rows.length,2)
assert.equal(merged.duplicates.length,1)
assert.equal(createTransferDuplicateKey(manual),manual.duplicateKey)
const internal=normalizeManualTransfer({club:'FC Twente',playerName:'Interne Speler',from:'Ajax',to:'FC Twente',type:'definitief'})
const internalClubs=buildTransferClubRows([internal],[])
assert.equal(internalClubs.find(row=>row.club==='Ajax').outgoing.length,1)
assert.equal(internalClubs.find(row=>row.club==='FC Twente').incoming.length,1)
assert.equal(internalClubs.find(row=>row.club==='Ajax').outgoing[0].id,internalClubs.find(row=>row.club==='FC Twente').incoming[0].id)
const ranked=sortTransferClubRanking([{club:'PSV'},{club:'Ajax'},{club:'AZ'}],club=>({PSV:{score:80,verdict:'gelijk'},Ajax:{score:80,verdict:'sterker'},AZ:{score:90,verdict:'zwakker'}}[club]))
assert.deepEqual(ranked.map(row=>row.club),['AZ','Ajax','PSV'])
assert.equal(stepTransferClubIndex(17,'next'),0)
assert.equal(stepTransferClubIndex(0,'previous'),17)
console.log('Transfer Deadline Data-tests geslaagd.')
