import { renderPersonalContext } from './personalContext.js'
import { buildCaptainRadar } from '../services/captainRadarEngine.js'
import { getManagerTeamState } from './optimizer.js'
import { selectionPlayers, playerId } from '../services/personalSelection.js'
import { getPlayers } from '../services/database.js'
import { safeHtml } from '../platform/html.js'
import { getDatabaseSummary, getFixtures, getPlayerProfiles } from '../services/database.js'
import { buildDifferentialAnalysis } from '../services/differentialEngine.js'
import { getIntelligenceRound, getIntelligenceRounds } from '../services/intelligenceHelpers.js'
import { getPlayerDetailProfile, renderPlayerDetailProfile } from './players.js'
import { clubLogo, esc, fmt, opportunityMatrix, playerPhoto, positionLabel, scoreBar } from './intelligenceUi.js'

const state={season:'',round:0,horizon:3,threshold:10,sort:'edgeScore',direction:'desc',showAll:false,playerId:'',playerTab:'overview'}
function ensure(){const s=getDatabaseSummary();state.season ||= s.activeSeason||getPlayerProfiles()[0]?.season||'';const rounds=getIntelligenceRounds(state.season);if(!rounds.includes(Number(state.round)))state.round=getIntelligenceRound(state.season);return rounds}
const filter=(label,key,values,current,format=v=>v)=>`<label><span>${label}</span><select data-diff-filter="${key}">${values.map(v=>`<option value="${esc(v)}" ${String(v)===String(current)?'selected':''}>${esc(format(v))}</option>`).join('')}</select></label>`
function explanation(p,type){if(type==='safe')return `Van de overige low-owned opties biedt ${p.name} de sterkste combinatie van minuten, betrouwbaarheid en projectie.`;if(type==='budget')return `Binnen zijn positie combineert ${p.name} een lage prijs met bovengemiddelde projectiewaarde.`;return `Slechts ${fmt(p.ownership)}% gekozen terwijl zijn projectie en wedstrijdprofiel een Edge Score van ${fmt(p.edgeScore,0)} opleveren.`}
function hero(type,label,p){if(!p)return `<article class="diff-hero ${type} empty"><span>${label}</span><h3>Geen overtuigende kandidaat</h3><p>Geen speler voldoet binnen deze filters aan de kwaliteitsgrens.</p></article>`;const badges=[p.xpScore>=75&&'🎯 Hoge projectie',p.availability>=85&&'🛡 Veilige minuten',p.valueScore>=75&&'💰 Value',p.projection.dgwCount&&'📅 DGW',p.availability<55&&'⚠ Minutenrisico'].filter(Boolean).slice(0,3);return `<article class="diff-hero ${type}" data-intel-player="${esc(p.id)}"><header><span>${label}</span><b>${fmt(p.edgeScore,0)}</b></header><div class="diff-player">${playerPhoto(p,'diff-photo')}<div><h3>${esc(p.name)}${selectionPlayers(getManagerTeamState(),getPlayers()).some(o=>playerId(o)===String(p.id))?' <span class="owned-badge">In jouw selectie</span>':''}</h3><p>${clubLogo(p.club)} ${esc(p.club)} · ${esc(positionLabel(p.position))}</p><small>${fmt(p.expectedPoints)} xP · ${fmt(p.expectedMinutes,0)} xMin</small></div></div><div class="diff-stats"><span><small>Gekozen</small><b>${fmt(p.ownership)}%</b></span><span><small>Fixture</small><b>${fmt(p.fixtureScore,0)}</b></span><span><small>Vorm</small><b>${fmt(p.formScore,0)}</b></span><span><small>Huidige prijs</small><b>€ ${fmt(p.price)} mln</b></span></div><div class="diff-badges">${badges.map(x=>`<span>${x}</span>`).join('')}</div><p>${esc(explanation(p,type))}</p>${scoreBar(type==='safe'?p.safeDifferentialScore:p.edgeScore,'Edge Score')}</article>`}
function ranking(d){let rows=[...d.ranking];const factor=state.direction==='asc'?1:-1;rows.sort((a,b)=>((Number(a[state.sort])||0)-(Number(b[state.sort])||0))*factor||a.name.localeCompare(b.name,'nl'));if(!state.showAll)rows=rows.slice(0,10);const columns=[['edgeScore','Edge'],['expectedPoints','xP'],['expectedMinutes','xMin'],['ownership','Ownership'],['fixtureScore','Fixture'],['formScore','Vorm'],['valueScore','Value'],['price','Huidige prijs']];return `<section class="panel intel-table diff-ranking"><div class="intel-section-head"><div><span class="eyebrow">Top ${state.showAll?'alle':'10'}</span><h3>Differential-ranking</h3></div><button data-diff-all>${state.showAll?'Toon top 10':'Toon alle'}</button></div><table><thead><tr><th>#</th><th>Speler</th><th>Club</th><th>Positie</th>${columns.map(([k,l])=>`<th><button data-diff-sort="${k}" class="${state.sort===k?'active':''}">${l}${state.sort===k?(state.direction==='desc'?' ↓':' ↑'):''}</button></th>`).join('')}</tr></thead><tbody>${rows.map((p,i)=>`<tr data-intel-player="${esc(p.id)}"><td>${i+1}</td><td><span class="table-player">${playerPhoto(p,'intel-mini-photo')}<b>${esc(p.name)}</b></span></td><td>${clubLogo(p.club)} ${esc(p.club)}</td><td>${esc(positionLabel(p.position))}</td><td><b class="edge-pill">${fmt(p.edgeScore,0)}</b></td><td>${fmt(p.expectedPoints)}</td><td>${fmt(p.expectedMinutes,0)}</td><td>${fmt(p.ownership)}%</td><td>${fmt(p.fixtureScore,0)}</td><td>${fmt(p.formScore,0)}</td><td>${fmt(p.valueScore,0)}</td><td>€ ${fmt(p.price)} mln</td></tr>`).join('')}</tbody></table>${rows.length?'':'<div class="intel-empty">Geen differential voldoet aan ownership- en kwaliteitsgrens.</div>'}</section>`}
function drawer(){if(!state.playerId)return'';const p=getPlayerDetailProfile({playerId:state.playerId,season:state.season});return p?`<div class="intel-backdrop" data-diff-close></div><aside class="intel-drawer"><header><span>Spelerprofiel</span><button data-diff-close>×</button></header><div>${renderPlayerDetailProfile(p,state.playerTab,{startRound:state.round,count:5,selectedFixtureId:null})}</div></aside>`:''}
export function createDifferentialsScreen(){const rounds=ensure(),d=buildDifferentialAnalysis({season:state.season,startRound:state.round,horizon:state.horizon,threshold:state.threshold}),seasons=[...new Set(getFixtures().map(f=>f.season).filter(Boolean))];return `${renderPersonalContext('differentials',buildCaptainRadar({season:state.season,round:state.round}))}<section class="intelligence-suite differentials-suite"><section class="diff-heading panel"><div><span class="eyebrow">FVT Intelligence Suite</span><h2>Differentials</h2><p>Low-owned spelers met echte projectie, minuten en fixturekwaliteit.</p></div><div class="intel-filters">${filter('Seizoen','season',seasons,state.season)}${filter('Startronde','round',rounds,state.round,v=>`SR${v}`)}${filter('Horizon','horizon',[1,3,5],state.horizon,v=>`${v} ronde${v===1?'':'s'}`)}${filter('Ownership','threshold',[5,10,15],state.threshold,v=>`< ${v}%`)}</div></section><section class="diff-heroes">${hero('best','💎 Beste differential',d.heroes.best)}${hero('safe','🛡 Veiligste alternatief',d.heroes.safe)}${hero('budget','💰 Budget differential',d.heroes.budget)}</section><section class="panel"><span class="eyebrow">Opportunity Matrix</span><h3>Waar zit de low-owned edge?</h3>${opportunityMatrix(d.matrix,{highlight:{best:d.heroes.best?.id,safe:d.heroes.safe?.id,budget:d.heroes.budget?.id}})}</section>${ranking(d)}<section class="intel-grid two"><article class="panel"><span class="eyebrow">Beste per positie</span>${d.positions.map(x=>`<button class="position-edge" data-intel-player="${esc(x.player.id)}"><span>${positionLabel(x.position)}<small>${esc(x.player.name)}</small></span><b>${fmt(x.player.edgeScore,0)}</b></button>`).join('')||'<div class="intel-empty">Geen positionele edges.</div>'}</article><article class="panel"><span class="eyebrow">Differential clubs</span>${d.clubs.slice(0,8).map(c=>`<div class="club-edge">${clubLogo(c.club)}<span><b>${esc(c.club)}</b><small>${c.count} spelers · ${fmt(c.averageOwnership)}% gekozen</small></span><strong>${fmt(c.averageEdge,0)}</strong></div>`).join('')||'<div class="intel-empty">Geen club met meerdere sterke low-owned assets.</div>'}</article></section>${drawer()}</section>`}
function rerender(){const root=document.querySelector('#page-content');if(root){root.innerHTML=safeHtml(createDifferentialsScreen());mountDifferentialsScreen()}}
export function mountDifferentialsScreen(){document.querySelectorAll('[data-diff-filter]').forEach(x=>x.addEventListener('change',()=>{const k=x.dataset.diffFilter;state[k]=['round','horizon','threshold'].includes(k)?Number(x.value):x.value;if(k==='season')state.round=0;state.showAll=false;rerender()}));document.querySelectorAll('[data-diff-sort]').forEach(x=>x.addEventListener('click',e=>{e.stopPropagation();const k=x.dataset.diffSort;state.direction=state.sort===k&&state.direction==='desc'?'asc':'desc';state.sort=k;rerender()}));document.querySelector('[data-diff-all]')?.addEventListener('click',()=>{state.showAll=!state.showAll;rerender()});document.querySelectorAll('[data-intel-player]').forEach(x=>x.addEventListener('click',()=>{state.playerId=x.dataset.intelPlayer;rerender()}));document.querySelectorAll('[data-diff-close]').forEach(x=>x.addEventListener('click',()=>{state.playerId='';rerender()}));document.querySelectorAll('.intel-drawer [data-player-detail-tab]').forEach(x=>x.addEventListener('click',()=>{state.playerTab=x.dataset.playerDetailTab;rerender()}))}
