import { renderPlayerAvatar } from '../services/playerPhotos.js'
import { availabilityPolicy } from '../services/availability.js'
export { logoSlug } from '../services/clubIdentity.js'
import { logoSlug } from '../services/clubIdentity.js'

export const esc = (value) => String(value ?? '').replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#039;')
export const fmt = (value, digits = 1) => value === null || value === undefined || value === '' || !Number.isFinite(Number(value)) ? '—' : Number(value).toLocaleString('nl-NL', { minimumFractionDigits: digits, maximumFractionDigits: digits })
export const positionLabel = (value) => ({ keeper: 'Doelman', verdediger: 'Verdediger', middenvelder: 'Middenvelder', aanvaller: 'Aanvaller' }[String(value ?? '').toLowerCase()] ?? value ?? 'Speler')
export const clubLogo = (club) => `<img class="intel-club-logo" src="./club-logos/${logoSlug(club)}.png" alt="${esc(club)}" onerror="this.hidden=true">`
export function playerPhoto(player, className = 'intel-player-photo') { return renderPlayerAvatar(player, { className, size: className.includes('mini') ? 32 : 64 }) }
export function scoreBar(value, label = '') { return `<div class="intel-scorebar" title="${esc(label)} ${fmt(value, 0)}/100"><i style="--score:${Math.max(0, Math.min(100, Number(value) || 0))}%"></i></div>` }
export function playerLine(player, scoreKey = 'trajectoryScore') { return `<button class="intel-player-line" data-intel-player="${esc(player.id)}"><span>${playerPhoto(player, 'intel-mini-photo')}<span><strong>${esc(player.name)}</strong><small>${esc(player.club)} · ${esc(positionLabel(player.position))}</small>${availabilityPolicy(player).reason?`<small>${esc(availabilityPolicy(player).reason)}</small>`:''}</span></span><b>${fmt(player[scoreKey], 0)}</b></button>` }
function opportunityMatrixBase(points, { highlight = {} } = {}) {
  if (!points.length) return '<div class="intel-empty">Onvoldoende data voor de opportunity matrix.</div>'
  const numeric = points.filter((p) => Number.isFinite(Number(p.x)) && Number.isFinite(Number(p.y)))
  const maxX = Math.max(15, ...numeric.map((p) => Number(p.x))) * 1.06, maxY = Math.max(1, ...numeric.map((p) => Number(p.y))) * 1.08
  const median = (values) => [...values].sort((a,b)=>a-b)[Math.floor(values.length/2)] ?? 0
  const medianX = median(numeric.map((p)=>Number(p.x))), medianY = median(numeric.map((p)=>Number(p.y)))
  const chosen = new Set(Object.values(highlight).filter(Boolean))
  for (const candidate of [[...numeric].sort((a,b)=>(b.underRadarScore||0)-(a.underRadarScore||0))[0],[...numeric].sort((a,b)=>(b.score||0)-(a.score||0))[0],[...numeric].sort((a,b)=>(b.trapScore||0)-(a.trapScore||0))[0],[...numeric].sort((a,b)=>b.y-a.y)[0]]) if(candidate && chosen.size<5) chosen.add(candidate.id)
  const coords = (p) => ({ x: Math.max(68,Math.min(746,60+Number(p.x)/maxX*700)), y: Math.max(34,Math.min(332,340-Number(p.y)/maxY*300)) })
  return `<div class="intel-matrix"><div class="matrix-label tl">Weinig gekozen · hoge projectie</div><div class="matrix-label tr">Populair · hoge projectie</div><div class="matrix-label bl">Weinig gekozen · lage projectie</div><div class="matrix-label br">Populair · lage projectie</div><svg viewBox="0 0 800 380" role="img" aria-label="Populariteit tegenover verwachte punten"><line x1="${60 + medianX/maxX*700}" y1="25" x2="${60 + medianX/maxX*700}" y2="340"/><line x1="60" y1="${340 - medianY/maxY*300}" x2="760" y2="${340 - medianY/maxY*300}"/>${numeric.map((p) => { const {x,y}=coords(p),r=Math.max(5,Math.min(15,Number(p.size)||5)); const active=chosen.has(p.id); return `<g><circle data-intel-player="${esc(p.id)}" tabindex="0" cx="${x}" cy="${y}" r="${r}" class="${active?'is-highlight':''}" style="--fixture:${Number.isFinite(Number(p.fixture))?Number(p.fixture):50}" aria-label="${esc(p.name)}, ${fmt(p.x)} procent gekozen, ${fmt(p.y)} verwachte punten"><title>${esc(p.name)} · ${esc(p.club)} · ${positionLabel(p.position)} · ${fmt(p.y)} xP · ${fmt(p.expectedMinutes,0)} min · ${fmt(p.x)}% gekozen · € ${fmt(p.size)} mln · schema ${fmt(p.fixture,0)} · zekerheid ${fmt(p.reliability,0)}</title></circle>${active?`<text class="matrix-point-label" x="${Math.min(720,x+12)}" y="${Math.max(24,y-10)}">${esc(p.name)}</text>`:''}</g>` }).join('')}</svg><span class="matrix-axis x">Populariteit →</span><span class="matrix-axis y">Verwachte punten →</span><div class="matrix-legend"><span>Cirkelgrootte = prijs</span><span>Rood = zwaar schema</span><span>Groen = gunstig schema</span></div></div>`
}
export function opportunityMatrix(points, options={}){return opportunityMatrixBase(points,options).replaceAll('hoge projectie','hoge verwachting').replaceAll('lage projectie','lage verwachting').replace('<div class="matrix-legend"><span>Cirkelgrootte = prijs</span><span>Rood = zwaar schema</span><span>Groen = gunstig schema</span></div>','<div class="matrix-legend"><span class="matrix-legend-group"><b>Kleur</b><i class="legend-dot easy"></i>gunstiger <i class="legend-dot average"></i>gemiddeld <i class="legend-dot hard"></i>moeilijker</span><span class="matrix-legend-group"><b>Grootte</b>grotere cirkel = hogere prijs</span><span class="matrix-legend-group"><b>Assen</b>links minder gekozen · rechts meer gekozen · onder minder xP · boven meer xP</span><span class="matrix-legend-group"><b>Stippellijnen</b>verdelen de huidige markt in vier groepen</span></div>')}
