import { getPlayers, getDatabaseSummary } from '../services/database.js'
import { buildCaptainRadar, getCaptainRadarDefaultRound } from '../services/captainRadarEngine.js'
import { getManagerTeamState } from './optimizer.js'
import { personalAdvice, playerId, playerPrice, selectionLineup } from '../services/personalSelection.js'
import { esc } from './selection.js'
import { getPlayerRoundProjection } from '../services/optimizer/optimizerLineup.js'

export function renderPersonalContext(screen, radar = null) {
  const state = getManagerTeamState(), players=getPlayers(), season=getDatabaseSummary().activeSeason || players[0]?.season
  const data = radar ?? buildCaptainRadar({season,round:getCaptainRadarDefaultRound(season)})
  const projections = data.candidates.map(p => ({ p, rounds:Array.from({length:Math.min(3,35-data.round)},(_,i)=>getPlayerRoundProjection(p,data.round+i)) }))
  const horizonCount = Math.min(3,35-data.round)
  const future = projections.filter(({rounds})=>rounds.length && rounds.every(r=>r.hasProjection)).map(({p,rounds})=>({...p,expectedPoints:rounds.reduce((s,r)=>s+r.expectedPoints,0),expectedMinutes:rounds.reduce((s,r)=>s+r.expectedMinutes,0)}))
  const ownedIds = new Set((state.importResult?.players??[]).map(r=>playerId(r.player)))
  const completeHorizon = [...ownedIds].every(id=>future.some(p=>playerId(p)===id)) && future.length > 0
  const advice=personalAdvice({state,players,candidates:data.candidates,horizonCandidates:completeHorizon?future:data.candidates})
  if(!advice.owned.length) return `<section class="panel personal-context"><span class="eyebrow">Persoonlijke Studio</span><h3>Maak je advies persoonlijk</h3><p>Voeg je spelers toe om je eigen captain, risico’s en transfers te beoordelen.</p><a href="/studio/selection">Mijn selectie samenstellen →</a></section>`
  const lineup=selectionLineup(state,advice.owned),byId=new Map(players.map(p=>[playerId(p),p])), best=advice.captains[0], transfer=advice.transfers[0]
  const candidate = p => p?`<strong>${esc(p.name)}</strong><span>${Number(p.radarScore).toFixed(1)} / 100 · ${Number(p.expectedPoints).toFixed(1)} xP · ${Math.round(p.expectedMinutes)} verwachte minuten</span><small>${p.fixtures.map(f=>`${esc(f.opponent)} (${f.isHome?'thuis':'uit'})`).join(' · ')||'Geen wedstrijd'}</small><p>${esc(p.reasons?.[0]||'Gebaseerd op de rondeprojectie en verwachte speeltijd.')}</p>${p.expectedMinutes/Math.max(1,p.fixtureCount)<60?'<small>Let op: beperkte minutenverwachting.</small>':''}`:'<p>Geen geschikte captain met voldoende minutenprojectie in deze ronde.</p>'
  const captain=`<article class="personal-advice-card"><span class="eyebrow">Jouw beste captain</span>${candidate(best)}${best&&!lineup.starters.includes(playerId(best))?'<p>Zet deze speler eerst in je basis voordat je hem captain maakt.</p>':''}${advice.captains.length>1?`<details><summary>Alternatieven uit jouw selectie</summary>${advice.captains.slice(1,4).map(p=>`<div>${candidate(p)}</div>`).join('')}</details>`:''}</article>`
  let content = captain
  if(screen==='fixtures') {
    const clubs=[...new Set(advice.owned.map(p=>p.club))]
    content=`<div class="personal-clubs">${clubs.map(club=>{const clubPlayers=advice.owned.filter(p=>p.club===club),c=data.candidates.find(p=>p.club===club);return `<article class="personal-advice-card"><strong>${esc(club)} · ${clubPlayers.length} spelers</strong><p>${clubPlayers.map(p=>esc(p.name)).join(', ')}</p><span>${c?.fixtures.map(f=>`${esc(f.opponent)} (${f.isHome?'T':'U'})`).join(' · ')||'Lege speelronde'}</span><small>${c?.fixtureCount>1?'Dubbele speelronde':c?.fixtureScore<4?'Moeilijke wedstrijd volgens het bestaande model':'Bekijk het volledige programma hieronder'}</small></article>`}).join('')}</div>`
  } else if(screen==='differentials') {
    const differential = data.candidates.filter(p=>p.selectedPct<=10).sort((a,b)=>Number(advice.owned.some(o=>playerId(o)===playerId(a)))-Number(advice.owned.some(o=>playerId(o)===playerId(b)))||b.radarScore-a.radarScore).slice(0,6)
    content=differential.map(p=>`<article class="personal-advice-card"><strong>${esc(p.name)} ${advice.owned.some(o=>playerId(o)===playerId(p))?'<span class="owned-badge">In jouw selectie</span>':''}</strong><span>${p.selectedPct}% gekozen · ${p.expectedPoints.toFixed(1)} xP</span><small>${esc(p.club)} · ${esc(p.position)}</small></article>`).join('')
  } else if(screen!=='captain') {
    content+=`<article class="personal-advice-card"><span class="eyebrow">Persoonlijk transferadvies</span>${transfer?`<strong>UIT ${esc(transfer.out.name)} → IN ${esc(transfer.incoming.name)}</strong><p>+${transfer.gain.toFixed(1)} verwachte punten ${completeHorizon?`over speelronde ${data.round}–${data.round+horizonCount-1}`:`in speelronde ${data.round}`}, na ${transfer.pointsCost} transferstrafpunten; dezelfde positie en maximaal drie spelers per club.</p><small>Verkoopkandidaat: ${Math.round(transfer.out.expectedMinutes)} verwachte minuten · vormscore ${Number(transfer.out.formScore).toFixed(1)} · ${transfer.out.fixtures.map(f=>esc(f.opponent)).join(', ')||'geen wedstrijd'}. Vervanger: ${transfer.incoming.expectedPoints.toFixed(1)} xP over de adviesperiode.</small><span>Extra budget nodig: € ${transfer.cost.toFixed(1)}${transfer.budgetConfirmed?' · binnen je opgegeven budget':' · budget nog niet bevestigd'}</span><small>${transfer.priceEstimated?'Verkoopwaarde geschat op marktprijs; vul je echte verkoopwaarde in.':'Gebaseerd op je opgegeven prijzen.'} Advies, geen uitgevoerde transfer.</small><button class="platform-primary" data-plan-out="${esc(playerId(transfer.out))}" data-plan-in="${esc(playerId(transfer.incoming))}">Bewaar als transferplan</button>`:'<p>Geen aantoonbaar betere vervanger binnen de bekende voorwaarden. Behoud je selectie of vul je budget aan.</p>'}</article><article class="personal-advice-card"><span class="eyebrow">Jouw grootste minutenrisico</span>${advice.risk?`<strong>${esc(advice.risk.name)}</strong><span>${Math.round(advice.risk.expectedMinutes)} verwachte minuten · ${advice.risk.expectedPoints.toFixed(1)} xP</span><p>${esc(advice.risk.form?.label??'Controleer beschikbaarheid en de komende wedstrijden.')}</p>`:'<p>Onvoldoende projectiedata.</p>'}</article>`
  }
  return `<section class="panel personal-context" data-personal-context="${screen}"><div class="personal-context-heading"><div><span class="eyebrow">Jouw selectie · speelronde ${data.round}</span><h3>${screen==='captain'?'Jouw beste captain':screen==='differentials'?'Differentials voor jouw selectie':screen==='fixtures'?'Jouw spelers in het speelschema':'Jouw selectieadvies'}</h3><p>${advice.owned.length}/15 spelers · C ${esc(byId.get(lineup.captainId)?.name||'nog niet gekozen')} · VC ${esc(byId.get(lineup.viceCaptainId)?.name||'nog niet gekozen')} · Marktwaarde € ${advice.owned.reduce((sum,p)=>sum+(playerPrice(p)??0),0).toFixed(1)} · ${state.bankKnown?`€ ${Number(state.bank).toFixed(1)} beschikbaar`:'Budget onbekend'}</p></div><a href="/studio/selection">Selectie beheren →</a></div><div class="personal-advice-grid">${content}</div>${(state.plannedTransfers??[]).length?`<div class="personal-plans"><h4>Geplande transfers · nog niet uitgevoerd</h4>${state.plannedTransfers.map((t,i)=>`<p>UIT ${esc(byId.get(t.outId)?.name??t.outId)} → IN ${esc(byId.get(t.inId)?.name??t.inId)} <button data-remove-plan="${i}">Plan verwijderen</button></p>`).join('')}</div>`:''}${advice.owned.length<15?'<p>Je selectie is nog niet compleet; adviezen gebruiken de al gekozen spelers.</p>':''}</section>`
}
