import {pressureDirection,directionalChance,pressureStatus,hasRemainingRange,presentedExpectedPrice} from '../services/pricePresentation.js'
export const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
export const number=v=>v==null?'—':Number(v).toLocaleString('nl-NL',{maximumFractionDigits:1})
export const money=v=>v==null?'—':`€ ${(v/10).toLocaleString('nl-NL',{minimumFractionDigits:1,maximumFractionDigits:1})}`
export const percent=v=>v==null?'Onvoldoende data':`${number(v)}%`
export const date=v=>v?new Date(v).toLocaleString('nl-NL',{timeZone:'Etc/GMT-1',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}):'Onbekend'
export const clock=v=>new Date(v).toLocaleTimeString('nl-NL',{timeZone:'Etc/GMT-1',hour:'2-digit',minute:'2-digit'})
export const arrow=p=>pressureDirection(p)==='rise'?'↑':pressureDirection(p)==='fall'?'↓':'—'
export const confidence=p=>p.confidence_score==null?'Onvoldoende data':`${number(p.confidence_score)}/100 · ${p.confidence_label||p.confidence||'Onbekend'}`
export const remaining=p=>{if(p.estimated_remaining_net_transfers==null||pressureDirection(p)==='stable')return 'Onvoldoende drempeldata';const r=p.estimated_remaining_range;return `${hasRemainingRange(p)?`${number(r[0])}–${number(r[1])}`:`±${number(p.estimated_remaining_net_transfers)}`} netto ${pressureDirection(p)==='fall'?'verkopen':'aankopen'}`}
export const metric=(label,value,note='')=>`<article class="pp-metric"><small>${esc(label)}</small><strong>${esc(value)}</strong>${note?`<span>${esc(note)}</span>`:''}</article>`
const tips={pressure:'Prijsdruk vergelijkt de actuele transferbeweging met de historisch geschatte drempel voor een prijswijziging. 100% betekent dat de geschatte historische drempel is bereikt. Dit is geen gegarandeerde ESPN-grens.',remaining:'Geschatte resterende netto transfers tot de historische drempel. Dit is een modelrange, geen officiële ESPN-drempel.',confidence:'Confidence geeft aan hoe betrouwbaar de onderliggende data en modelinschatting zijn. Het is niet hetzelfde als de kans op een prijswijziging.',chance:'Modelkans komt uit historische kanskalibratie. Een sterk drempelsignaal kan samengaan met een lage modelkans.'}
export const info=key=>`<span class="pp-info" tabindex="0" role="note" aria-label="${esc(tips[key])}">ⓘ<span class="pp-tooltip">${esc(tips[key])}</span></span>`
export const bar=(value,kind)=>value==null?'':`<span class="pp-bar ${esc(kind)} ${value>=100?'pp-over':''}" aria-hidden="true"><i style="width:${Math.min(100,Math.max(0,value))}%"></i></span>`
const directionWord=p=>pressureDirection(p)==='rise'?'Stijgingsdruk':pressureDirection(p)==='fall'?'Dalingsdruk':'Geen gerichte druk'
const boundary=p=>p.price_pressure_percentage>=100?'Geschatte historische grens bereikt':p.price_pressure_percentage>=80?'Dicht bij de geschatte grens':p.price_pressure_percentage==null?'Geschatte drempel nog onbekend':'Onder de geschatte grens'
export const signalClass=p=>`pp-signal ${pressureDirection(p)} ${p.price_pressure_percentage>=100?'pp-over':''}`
export const chip=p=>`<span class="pp-chip ${pressureDirection(p)}">${arrow(p)} ${esc(pressureStatus(p))}</span>`
export function probability(p){const value=directionalChance(p);return `<span class="pp-probability ${value!=null&&value<10?'pp-low':''}">${percent(value)}</span>${value>=10?bar(value,`${pressureDirection(p)} pp-prob-bar ${value>=70?'pp-high':value<40?'pp-small':''}`):''}`}
export function priceRow(p,i,selected){return `<tr class="${signalClass(p)} ${p.player_id===selected?'selected':''}" data-pp-direction="${pressureDirection(p)}"><td class="pp-rank">${i+1}</td><td class="pp-player-cell"><button data-pp-player="${p.player_id}" aria-pressed="${p.player_id===selected}">${esc(p.name)}</button><small class="pp-mobile-club">${esc(p.club)} · ${money(p.current_price)}</small></td><td class="pp-club-cell">${esc(p.club)}</td><td class="pp-price-cell">${money(p.current_price)}</td><td class="pp-status-cell">${chip(p)}</td><td class="pp-pressure-cell" data-label="Prijsdruk"><strong>${arrow(p)} ${p.price_pressure_percentage==null?'—':percent(p.price_pressure_percentage)}</strong>${bar(p.price_pressure_percentage,pressureDirection(p))}${p.price_pressure_percentage>=100?'<small class="pp-boundary">Over geschatte grens</small>':''}</td><td class="pp-remaining-cell" data-label="Geschat nog nodig"><strong>${remaining(p)}</strong>${hasRemainingRange(p)?'<small>Brede onzekerheidsmarge</small>':''}</td><td class="pp-chance-cell" data-label="Modelkans">${probability(p)}</td><td class="pp-confidence-cell" data-label="Confidence">${esc(confidence(p))}</td><td class="pp-update-cell">${clock(p.expected_update_window.start)}–${clock(p.expected_update_window.end)}</td><td class="pp-trend-cell">${arrow(p)}</td></tr>`}
export function nearCard(p){return `<button class="${signalClass(p)}" data-pp-player="${p.player_id}" data-pp-direction="${pressureDirection(p)}"><strong>${esc(p.name)}</strong><span>${esc(p.club)}</span><b>${arrow(p)} ${percent(p.price_pressure_percentage)} ${directionWord(p).toLowerCase()}</b>${bar(p.price_pressure_percentage,pressureDirection(p))}<span class="pp-boundary">${boundary(p)}</span><span>Geschat nog</span><strong>${remaining(p)}</strong>${hasRemainingRange(p)?'<small>Brede onzekerheidsmarge</small>':''}<small>Confidence ${esc(confidence(p))}</small><small>Modelkans ${percent(directionalChance(p))}</small></button>`}
export function priceDetail(p){
 if(!p)return '<aside class="pp-panel pp-detail"><p>Geen spelers bij deze filters. Kies een andere view of zoekopdracht.</p></aside>'
 const dir=pressureDirection(p),expected=presentedExpectedPrice(p)
 return `<aside class="pp-panel pp-detail ${signalClass(p)}" data-pp-direction="${dir}" aria-label="Spelerdetail"><header><span class="pp-avatar">${esc(p.name.slice(0,2).toUpperCase())}</span><div><h3>${esc(p.name)}</h3><p>${esc(p.club)}</p>${chip(p)}</div></header>
 <div class="pp-pair">${metric('Huidige prijs',money(p.current_price))}${metric('Verwachte prijs',expected==null?'Nog geen prijswijziging voorspeld':money(expected))}</div>
 <section class="pp-pressure-hero ${signalClass(p)}"><span>Drempelsignaal ${info('pressure')}</span><h4>${directionWord(p)}</h4><b>${arrow(p)} ${p.price_pressure_percentage==null?'—':percent(p.price_pressure_percentage)}</b>${bar(p.price_pressure_percentage,dir)}<strong>${esc(pressureStatus(p))}</strong><span>${boundary(p)}</span><small>Een historische schatting, geen officiële ESPN-grens.</small></section>
 <section class="pp-remaining-hero"><h4>Geschat nog nodig ${info('remaining')}</h4><strong>${remaining(p)}</strong>${hasRemainingRange(p)?'<span>Brede onzekerheidsmarge</span>':''}</section>
 <div class="pp-pair pp-secondary"><section class="pp-metric"><small>Modelkans ${info('chance')}</small>${probability(p)}<span>${dir==='stable'?'Geen gerichte voorspelling':`Op ${dir==='rise'?'stijging':'daling'}`}</span>${directionalChance(p)!=null&&directionalChance(p)<10?'<span>Het kansmodel is nog conservatief gekalibreerd.</span>':''}</section><section class="pp-metric"><small>Betrouwbaarheid ${info('confidence')}</small><strong>${esc(confidence(p))}</strong><span>Datakwaliteit en modelbasis; geen kans op wijziging.</span></section></div>
 <div class="pp-pair">${metric('Updatevenster',`${clock(p.expected_update_window.start)}–${clock(p.expected_update_window.end)}`)}${metric('Laatste echte wijziging',date(p.last_price_change))}</div>
 <details class="pp-inset pp-explanation"><summary>Historie & modeluitleg</summary><ul><li>Netto transfers sinds referentie: ${number(p.net_transfers_since_reset)}</li><li>Ownership referentie: ${number(p.reset?.ownership)}% · nu ${number(p.ownership)}%</li><li>Referentiemoment: ${date(p.reset?.captured_at)} (${p.reset_confirmed?'prijswijziging':'voorlopig'})</li><li>Geschatte drempel: ${p.threshold_unit==='ownership_fraction'?percent(p.estimated_threshold==null?null:p.estimated_threshold*100)+' relatief ownershipverlies':number(p.estimated_threshold)+' netto transfers'}</li><li>${number(p.threshold_samples)} drempelmetingen · threshold-confidence ${number(p.threshold_confidence_score)}/100</li><li>Kansbasis: ${esc(({comparable:'vergelijkbaar profiel',broader:'breder transferprofiel',season:'seizoensbasis',none:'nog geen historie'})[p.probability_basis]||'vorige modelversie')} · ${number(p.probability_sample_count)} gevallen / ${number(p.probability_window_count)} vensters</li><li>Vergelijkbaar profiel: ${number(p.comparable_historical_count)} eerder getoetste gevallen; ${number(p.comparable_historical_correct)} correcte uitkomsten</li><li>Historische hitrate vergelijkbaar profiel: ${p.comparable_historical_hitrate==null?'Te weinig vergelijkbare historische gevallen':percent(p.comparable_historical_hitrate)} (inclusief stabiel)</li><li>Metingen sinds referentie: ${number(p.snapshot_count_since_reset)} · grootste meetgat ${number(p.max_gap_minutes)} minuten</li><li>Beide modelkansen: stijging ${percent(p.rise_probability)} · daling ${percent(p.fall_probability)}</li></ul><p>Empirische schatting, geen bekende ESPN-formule. Ownership is afgerond; ‘nog nodig’ is een benadering. Een voorlopige referentie verlaagt de betrouwbaarheid.</p></details></aside>`
}
