import {supabase} from '../platform/client.js'
import {articleSlug,articleText} from '../services/articleContent.js'
import {uploadNewsImage,ownNewsImagePath,NEWS_IMAGE_BUCKET} from './newsImages.js'
import {PAGE_SIZE,STATES,value,may,editable,set,card,notice,empty,input,choose,yesNo,chip,when,localDate,cleanQuery,page,href,feedback,errorText,task,lockRow,pager,preview,esc,date} from './cmsUI.js'

export async function renderArticles(ctx){
 const params=new URLSearchParams(location.search),id=params.get('edit')
 if(id||params.has('new'))return articleForm(ctx,id)
 const categories=value(await supabase.from('news_categories').select('id,name').order('name')),q=cleanQuery(params.get('q')),state=params.get('status')||'',category=params.get('category')||'',current=page()
 let query=supabase.from('news_articles').select('id,title,slug,intro,category_id,status,author_name,featured,published_at,updated_at').order('updated_at',{ascending:false}).order('id').range(current*PAGE_SIZE,(current+1)*PAGE_SIZE)
 if(q)query=query.ilike('title','%'+q+'%');if(state)query=query.eq('status',state);if(category)query=query.eq('category_id',category)
 const rows=value(await query),visible=rows.slice(0,PAGE_SIZE)
 const listing=visible.length?`<div class="admin-table-wrap"><table class="cms-table cms-articles-table"><thead><tr>${['Artikel','Categorie','Status','Auteur','Datums','Acties'].map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${visible.map(a=>`<tr data-article-row="${a.id}"><td data-label="Artikel"><strong class="cms-row-title">${esc(a.title)}</strong><p class="cms-summary">${esc(a.intro||'Nog geen korte intro toegevoegd.')}</p><span class="cms-small">Uitgelicht: ${a.featured?'Ja':'Nee'}</span></td><td data-label="Categorie">${choose('Categorie wijzigen','category_'+a.id,[['','Geen categorie'],...categories.map(c=>[c.id,c.name])],a.category_id,`data-article-category="${a.id}" ${editable(ctx,a)?'':'disabled'}`)}</td><td data-label="Status">${chip(a.status)}</td><td data-label="Auteur">${esc(a.author_name||'FVT-redactie')}</td><td data-label="Datums"><span class="cms-small">Publicatie</span><span>${when(a.published_at)}</span><span class="cms-small">Laatst gewijzigd</span><span>${date(a.updated_at)}</span></td><td data-label="Acties"><div class="cms-row-actions"><a href="${href('nieuws','?edit='+a.id)}">${editable(ctx,a)?'Bewerken':'Bekijken'}</a><button type="button" data-news-preview="${a.id}">Preview</button>${editable(ctx,a)&&may(ctx,'articles.publish')&&!['published','scheduled'].includes(a.status)?`<button type="button" data-news-publish="${a.id}">Publiceren</button>`:''}${editable(ctx,a)&&may(ctx,'articles.unpublish')&&['published','scheduled'].includes(a.status)?`<button type="button" data-news-hide="${a.id}">Verbergen</button>`:''}${may(ctx,'articles.delete')?`<button type="button" class="admin-danger" data-news-delete="${a.id}">Verwijderen</button>`:''}</div></td></tr>`).join('')}</tbody></table></div>`:empty('Nog geen artikelen gevonden',q||state||category?'Pas je filters aan of maak een nieuw artikel.':'Begin met je eerste artikel via + Nieuw artikel.')
 set(ctx.root,card('Artikelen',`<div class="cms-overview-head"><p class="admin-muted">Schrijf, controleer en publiceer je nieuws op één plek.</p>${may(ctx,'articles.create')?`<a class="cms-primary-link" href="${href('nieuws','?new=1')}">+ Nieuw artikel</a>`:''}</div><form method="get" class="admin-filters cms-filters">${input('Zoeken','q',q,'type="search" placeholder="Zoek op titel" maxlength="100"')}${choose('Categorie','category',[['','Alle categorieën'],...categories.map(c=>[c.id,c.name])],category)}${choose('Status','status',[['','Alle statussen'],...Object.entries(STATES)],state)}<button type="submit">Toepassen</button>${q||state||category?`<a href="${href('nieuws')}">Filters wissen</a>`:''}</form>${listing}${pager('nieuws',current,rows.length>PAGE_SIZE,params)}${notice}`))
 const update=async(a,payload)=>value(await supabase.from('news_articles').update(payload).eq('id',a.id).eq('updated_at',a.updated_at).select('id').single())
 ctx.root.querySelectorAll('[data-news-preview]').forEach(button=>button.onclick=()=>task(ctx.root,button,async()=>{preview(value(await supabase.from('news_articles').select('*').eq('id',button.dataset.newsPreview).single()));feedback(ctx.root,'')}))
 for(const [attribute,operation]of [['newsPublish','publish'],['newsHide','hide'],['newsDelete','delete']])ctx.root.querySelectorAll(`[data-${attribute.replace(/[A-Z]/g,c=>'-'+c.toLowerCase())}]`).forEach(button=>button.onclick=()=>task(ctx.root,button,async()=>{
  const a=visible.find(row=>row.id===button.dataset[attribute])
  if(!await ctx.confirmAction(operation==='publish'?'Artikel publiceren':operation==='hide'?'Artikel verbergen':'Artikel verwijderen',operation==='delete'?`“${a.title}” wordt definitief verwijderd.`:operation==='hide'?`“${a.title}” verdwijnt uit het openbare nieuws.`:`“${a.title}” wordt zichtbaar op de website.`)){feedback(ctx.root,'');return}
  if(operation==='delete')value(await supabase.from('news_articles').delete().eq('id',a.id).eq('updated_at',a.updated_at).select('id').single())
  else if(operation==='hide')await update(a,{status:'hidden'})
  else {const full=value(await supabase.from('news_articles').select('body,intro,updated_at').eq('id',a.id).single());if(full.updated_at!==a.updated_at)throw Error('Dit artikel is inmiddels aangepast. Vernieuw het overzicht.');if(articleText(full.body).length<20||full.intro.trim().length<10)throw Error('Open het artikel en vul eerst de korte intro en artikeltekst aan.');await update(a,{status:'published',published_at:new Date(Date.now()-1000).toISOString()})}
  await renderArticles(ctx)
 }))
 ctx.root.querySelectorAll('[data-article-category]').forEach(select=>select.onchange=async()=>{const a=visible.find(row=>row.id===select.dataset.articleCategory),unlock=lockRow(select.closest('tr'));feedback(ctx.root,'Categorie opslaan…');try{await update(a,{category_id:select.value||null});await renderArticles(ctx)}catch(error){select.value=a.category_id||'';feedback(ctx.root,errorText(error))}finally{unlock()}})
}

async function articleForm(ctx,id){
 const article=id?value(await supabase.from('news_articles').select('*').eq('id',id).single()):{status:'draft',author_id:ctx.session.user.id}
 const categories=value(await supabase.from('news_categories').select('id,name').order('name')),canEdit=id?editable(ctx,article):may(ctx,'articles.create'),canPublish=may(ctx,'articles.publish')&&canEdit
 const states=canPublish?Object.entries(STATES):[['draft','Concept'],['review','Ter review'],...(!['draft','review'].includes(article.status)?[[article.status,STATES[article.status]]]:[])]
 const toolbar=[['p','Alinea'],['h2','H2'],['h3','H3'],['bold','Vet'],['italic','Cursief'],['link','Link'],['unlink','Link verwijderen'],['ul','Opsomming'],['ol','Genummerd'],['quote','Quote'],['undo','Ongedaan maken'],['redo','Opnieuw']].map(([command,label])=>`<button type="button" data-format="${command}" aria-label="${label}">${label}</button>`).join('')
 const fields=`${input('Titel','title',article.title,'required minlength="3" maxlength="180" placeholder="Geef je artikel een duidelijke titel"')}<label>Korte intro / samenvatting<textarea name="intro" maxlength="600" rows="3" aria-describedby="cms-intro-help">${esc(article.intro)}</textarea><small id="cms-intro-help" class="cms-help">Deze tekst wordt gebruikt op overzichtspagina's en artikelkaarten.</small></label><div class="cms-editor-field"><span id="cms-body-label">Artikeltekst</span><div class="cms-editor"><div id="cms-editor-toolbar" class="cms-editor-toolbar" role="toolbar" aria-label="Artikelopmaak">${toolbar}</div><div id="cms-body-editor" class="cms-body-editor"></div></div></div><div class="cms-image-field"><span>Afbeelding</span><div id="cms-image-drop" class="cms-image-drop"><div id="cms-image-preview"></div><p>Sleep een afbeelding hierheen of kies een bestand.</p><input type="file" id="cms-image-file" accept="image/jpeg,image/png,image/webp,.jpg,.jpeg,.png,.webp" aria-label="Artikelafbeelding kiezen"><small class="cms-help">JPG, PNG of WebP · maximaal 5 MB</small><div class="admin-actions"><button type="button" id="cms-image-remove">Afbeelding verwijderen</button></div><p id="cms-image-status" role="status" aria-live="polite"></p></div><input type="hidden" name="image_url" value="${esc(article.image_url)}"></div>${input('Afbeeldingsbeschrijving','image_alt',article.image_alt,'maxlength="250" placeholder="Beschrijf wat er op de afbeelding staat"')}<div class="admin-grid">${choose('Categorie','category_id',[['','Geen categorie'],...categories.map(c=>[c.id,c.name])],article.category_id)}${choose('Status','status',states,article.status)}${input('Publicatiedatum (lokale tijd)','published_at',localDate(article.published_at),'type="datetime-local" '+(canPublish?'':'disabled'))}${yesNo('Uitgelicht','featured',article.featured,canPublish?'':'disabled')}</div><details class="cms-advanced"><summary>Geavanceerd</summary>${input('Artikeladres','slug',article.slug||'','pattern="[a-z0-9]+(-[a-z0-9]+)*" maxlength="180" aria-describedby="cms-slug-help"')}<small id="cms-slug-help" class="cms-help">Bij nieuwe artikelen wordt dit adres automatisch gemaakt uit de titel. Bestaande artikeladressen blijven behouden.</small></details><p class="admin-muted">Auteur: ${esc(article.author_name||'FVT-redactie')}${id?' · Laatst gewijzigd: '+date(article.updated_at):''}</p>`
 const actions=`${canEdit?'<button type="submit" data-save="draft" class="admin-primary">Opslaan als concept</button>':''}<button type="button" id="article-preview">Voorbeeld</button>${canEdit?'<button type="submit" data-save="review">Ter review zetten</button>':''}${canPublish?'<button type="submit" data-save="publish" class="admin-primary">Publiceren</button>':''}${canEdit&&id?'<button type="submit" data-save="selected">Wijzigingen opslaan</button>':''}${id&&may(ctx,'articles.delete')?'<button type="button" id="article-delete" class="admin-danger">Verwijderen</button>':''}`
 set(ctx.root,card(id?'Artikel bewerken':'Nieuw artikel',`<a id="cms-back" href="${href('nieuws')}">← Terug naar artikelen</a>${!canEdit?'<p class="cms-notice">Dit artikel is alleen leesbaar voor jouw account. Vraag een publisher om het artikel eerst te depubliceren als je wijzigingen wilt maken.</p>':''}<form id="article-form" class="admin-form cms-article-form"><fieldset ${canEdit?'':'disabled'}>${fields}</fieldset><div class="cms-form-actions">${actions}</div>${notice}</form>`))
 const form=ctx.root.querySelector('#article-form'),{mountArticleEditor}=await import('./articleEditor.js'),editor=mountArticleEditor(ctx.root,article.body,!canEdit)
 let manualSlug=!!id,dirty=false,uploading=false,pendingUpload=null,disposed=false,saving=false
 const snapshot=()=>JSON.stringify({title:form.elements.fvt_title.value,intro:form.elements.intro.value,html:editor.html(),image:form.elements.image_url.value,alt:form.elements.image_alt.value,category:form.elements.category_id.value,status:form.elements.status.value,date:form.elements.published_at.value,featured:form.elements.featured.checked,slug:form.elements.slug.value})
 const initialSnapshot=snapshot()
 const markDirty=()=>{const changed=!disposed&&snapshot()!==initialSnapshot;if(changed!==dirty){dirty=changed;feedback(ctx.root,changed?'Niet-opgeslagen wijzigingen.':'')}};form.addEventListener('input',markDirty);form.addEventListener('change',markDirty);editor.onChange(markDirty)
 const beforeLeave=event=>{if(dirty&&!disposed){event.preventDefault();event.returnValue=''}};window.addEventListener('beforeunload',beforeLeave)
 form.elements.slug.oninput=()=>{manualSlug=true};form.elements.fvt_title.oninput=()=>{if(!manualSlug)form.elements.slug.value=articleSlug(form.elements.fvt_title.value)}
 const imagePreview=()=>{const url=form.elements.image_url.value;set(ctx.root.querySelector('#cms-image-preview'),url?`<img src="${esc(url)}" alt="${esc(form.elements.image_alt.value||'Artikelafbeelding')}" class="cms-upload-preview">`:'<p class="admin-muted">Nog geen afbeelding gekozen</p>');ctx.root.querySelector('#cms-image-remove').hidden=!url};imagePreview()
 const removePending=async()=>{if(pendingUpload){await supabase.storage.from(NEWS_IMAGE_BUCKET).remove([pendingUpload.path]);pendingUpload=null}}
 const busyUpload=busy=>{uploading=busy;form.querySelectorAll('[type=submit]').forEach(button=>button.disabled=busy||saving);ctx.root.querySelector('#cms-image-file').disabled=busy||saving||!canEdit;ctx.root.querySelector('#cms-image-remove').disabled=busy||saving||!canEdit}
 const upload=async file=>{if(uploading||saving||!canEdit)return;busyUpload(true);const message=ctx.root.querySelector('#cms-image-status');message.textContent='Afbeelding uploaden…';try{const uploaded=await uploadNewsImage(supabase,ctx.session.user.id,file);await removePending();pendingUpload=uploaded;form.elements.image_url.value=uploaded.url;markDirty();imagePreview();message.textContent='Afbeelding geüpload. Sla het artikel op om de wijziging te bewaren.'}catch(error){message.textContent=error.statusCode?'Uploaden is niet gelukt. Controleer je rechten en probeer opnieuw.':errorText(error)}finally{busyUpload(false);ctx.root.querySelector('#cms-image-file').value=''}}
 ctx.root.querySelector('#cms-image-file').onchange=event=>{const file=event.target.files[0];if(file)upload(file)}
 const drop=ctx.root.querySelector('#cms-image-drop');drop.ondragover=event=>{event.preventDefault();if(canEdit)drop.classList.add('is-dragging')};drop.ondragleave=()=>drop.classList.remove('is-dragging');drop.ondrop=event=>{event.preventDefault();drop.classList.remove('is-dragging');if(event.dataTransfer.files.length!==1){ctx.root.querySelector('#cms-image-status').textContent='Kies één afbeelding tegelijk.';return}upload(event.dataTransfer.files[0])}
 ctx.root.querySelector('#cms-image-remove').onclick=async()=>{if(!canEdit||uploading||saving)return;await removePending();form.elements.image_url.value='';markDirty();imagePreview();ctx.root.querySelector('#cms-image-status').textContent='Afbeelding verwijderd uit het formulier. Sla het artikel op om dit te bewaren.'}
 const formArticle=()=>({title:form.elements.fvt_title.value,intro:form.elements.intro.value,body:editor.body(),image_url:form.elements.image_url.value,image_alt:form.elements.image_alt.value,author_name:article.author_name||'FVT-redactie',published_at:article.published_at})
 ctx.root.querySelector('#article-preview').onclick=()=>{try{preview(formArticle())}catch(error){feedback(ctx.root,errorText(error))}}
 const leave=destination=>{disposed=true;dirty=false;window.removeEventListener('beforeunload',beforeLeave);editor.destroy();location.assign(destination)}
 ctx.root.querySelector('#cms-back').onclick=async event=>{event.preventDefault();if(saving||uploading)return;if(dirty&&!await ctx.confirmAction('Artikel verlaten','Onopgeslagen wijzigingen gaan verloren.'))return;await removePending();leave(href('nieuws'))}
 form.onsubmit=async event=>{
  event.preventDefault();if(!canEdit||uploading||saving)return
  const submitter=event.submitter||form.querySelector('[data-save=draft]'),operation=submitter.dataset.save
  saving=true;busyUpload(false)
  try{await task(ctx.root,submitter,async()=>{
   const payload={...formArticle(),category_id:form.elements.category_id.value||null,status:operation==='publish'?(form.elements.status.value==='scheduled'?'scheduled':'published'):operation==='selected'?form.elements.status.value:operation,slug:form.elements.slug.value||articleSlug(form.elements.fvt_title.value)}
   delete payload.author_name;delete payload.published_at
   if(canPublish){payload.featured=form.elements.featured.checked;payload.published_at=form.elements.published_at.value?new Date(form.elements.published_at.value).toISOString():['published','scheduled'].includes(payload.status)?new Date(Date.now()-1000).toISOString():null}
   if(payload.status==='scheduled'&&(!form.elements.published_at.value||Date.parse(payload.published_at)<=Date.now()))throw Error('Kies een publicatiedatum in de toekomst om dit artikel in te plannen.')
   if(['published','scheduled'].includes(payload.status)){if(articleText(payload.body).length<20||payload.intro.trim().length<10)throw Error('Vul een korte intro van minimaal 10 tekens en een artikeltekst van minimaal 20 tekens in.');if(!await ctx.confirmAction(payload.status==='scheduled'?'Artikel inplannen':'Artikel publiceren',payload.status==='scheduled'?`“${payload.title}” verschijnt vanaf ${when(payload.published_at)}.`:`“${payload.title}” wordt zichtbaar op de website.`)){feedback(ctx.root,'');return}}
   else if(['published','scheduled'].includes(article.status)&&!await ctx.confirmAction('Artikel depubliceren','Het artikel verdwijnt uit het openbare nieuws.')){feedback(ctx.root,'');return}
   let saved;const base=articleSlug(payload.title)
   for(let attempt=0;attempt<6;attempt++){const result=await(id?supabase.from('news_articles').update(payload).eq('id',id).eq('updated_at',article.updated_at):supabase.from('news_articles').insert(payload)).select('id').single();if(!result.error){saved=result.data;break}if(result.error.code!=='23505'||!String(result.error.message).includes('slug')||manualSlug||id)throw result.error;payload.slug=base+'-'+crypto.randomUUID().slice(0,8)}
   if(!saved)throw Error('Het artikeladres kon niet worden vastgelegd. Probeer opnieuw.')
   pendingUpload=null;const previousPath=ownNewsImagePath(supabase,ctx.session.user.id,article.image_url);if(previousPath&&article.image_url!==payload.image_url)await supabase.storage.from(NEWS_IMAGE_BUCKET).remove([previousPath])
   leave(href('nieuws','?edit='+saved.id+'&saved=1'))
  })}finally{saving=false;busyUpload(false)}
 }
 if(new URLSearchParams(location.search).has('saved'))feedback(ctx.root,'Artikel opgeslagen.')
 ctx.root.querySelector('#article-delete')?.addEventListener('click',event=>task(ctx.root,event.currentTarget,async()=>{if(saving||uploading)return;if(!await ctx.confirmAction('Artikel verwijderen',`“${article.title}” wordt definitief verwijderd.`)){feedback(ctx.root,'');return}value(await supabase.from('news_articles').delete().eq('id',id).eq('updated_at',article.updated_at).select('id').single());await removePending();const path=ownNewsImagePath(supabase,ctx.session.user.id,article.image_url);if(path)await supabase.storage.from(NEWS_IMAGE_BUCKET).remove([path]);leave(href('nieuws'))}))
}
