import {supabase} from '../platform/client.js'
import {VIDEO_CATEGORIES,videoCategory,thumbnailSources} from '../public/videoCatalog.js'
import {fetchVideoFeed} from '../public/videoFeed.js'
import {PAGE_SIZE,value,may,set,card,notice,empty,input,choose,yesNo,chip,localDate,cleanQuery,page,href,feedback,errorText,task,lockRow,pager,esc,date} from './cmsUI.js'

export async function renderVideos(ctx){
 const params=new URLSearchParams(location.search),id=params.get('edit');if(id||params.has('new'))return videoForm(ctx,id)
 const current=page(),q=cleanQuery(params.get('q')),category=params.get('category')||'',visibility=params.get('visibility')||''
 let query=supabase.from('site_videos').select('*').order('published_at',{ascending:false}).order('id').range(current*PAGE_SIZE,(current+1)*PAGE_SIZE)
 if(q)query=query.ilike('title','%'+q+'%');if(category)query=query.eq('category',category);if(visibility)query=query.eq('visible',visibility==='visible')
 const rows=value(await query),visible=rows.slice(0,PAGE_SIZE)
 const listing=visible.length?`<div class="admin-table-wrap"><table class="cms-table cms-videos-table"><thead><tr>${['Video','Rubriek','Publicatie','Zichtbaarheid','Acties'].map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${visible.map(v=>`<tr data-video-row="${v.id}"><td data-label="Video"><div class="cms-video-identity"><img data-cms-thumbnail="${v.youtube_id}" class="cms-video-thumb" src="${esc(v.thumbnail_url||thumbnailSources(v.youtube_id)[1])}" alt="${esc(v.title)}"><div><strong class="cms-row-title">${esc(v.title)}</strong><span class="cms-small">Uitgelicht: ${v.featured?'Ja':'Nee'}</span></div></div></td><td data-label="Rubriek">${choose('Rubriek wijzigen','category_'+v.id,VIDEO_CATEGORIES.map(c=>[c,c]),v.category,`data-video-category="${v.id}" ${may(ctx,'videos.edit')?'':'disabled'}`)}</td><td data-label="Publicatie">${date(v.published_at)}</td><td data-label="Zichtbaarheid">${v.visible?'<span class="admin-chip published">Zichtbaar</span>':chip('hidden')}</td><td data-label="Acties"><div class="cms-row-actions"><a href="${href('videos','?edit='+v.id)}">${may(ctx,'videos.edit')?'Bewerken':'Bekijken'}</a>${may(ctx,'videos.edit')&&may(ctx,v.visible?'videos.hide':'videos.publish')?`<button type="button" data-video-visibility="${v.id}">${v.visible?'Verbergen':'Zichtbaar maken'}</button>`:''}${may(ctx,'videos.delete')?`<button type="button" class="admin-danger" data-video-delete="${v.id}">Verwijderen</button>`:''}</div></td></tr>`).join('')}</tbody></table></div>`:empty('Nog geen video’s gevonden',q||category||visibility?'Pas je filters aan of voeg een video toe.':'Plak een YouTube-link via + Video toevoegen om je eerste video te registreren.')
 set(ctx.root,card('Video’s',`<div class="cms-overview-head"><p class="admin-muted">Beheer je afleveringen, rubrieken en zichtbaarheid.</p>${may(ctx,'videos.create')?`<a class="cms-primary-link" href="${href('videos','?new=1')}">+ Video toevoegen</a>`:''}</div><form method="get" class="admin-filters cms-filters">${input('Zoeken','q',q,'type="search" placeholder="Zoek op titel"')}${choose('Rubriek','category',[['','Alle rubrieken'],...VIDEO_CATEGORIES.map(c=>[c,c])],category)}${choose('Zichtbaarheid','visibility',[['','Alles'],['visible','Zichtbaar'],['hidden','Verborgen']],visibility)}<button type="submit">Toepassen</button></form>${listing}${pager('videos',current,rows.length>PAGE_SIZE,params)}${notice}`))
 const update=(v,payload)=>supabase.from('site_videos').update(payload).eq('id',v.id).eq('updated_at',v.updated_at).select('id').single().then(value)
 ctx.root.querySelectorAll('[data-video-category]').forEach(select=>select.onchange=async()=>{const v=visible.find(v=>v.id===select.dataset.videoCategory),unlock=lockRow(select.closest('tr'));feedback(ctx.root,'Rubriek opslaan…');try{await update(v,{category:select.value});await renderVideos(ctx)}catch(error){select.value=v.category;feedback(ctx.root,errorText(error))}finally{unlock()}})
 ctx.root.querySelectorAll('[data-video-visibility]').forEach(button=>button.onclick=()=>task(ctx.root,button,async()=>{const v=visible.find(v=>v.id===button.dataset.videoVisibility);await update(v,{visible:!v.visible});await renderVideos(ctx)}))
 ctx.root.querySelectorAll('[data-video-delete]').forEach(button=>button.onclick=()=>task(ctx.root,button,async()=>{const v=visible.find(v=>v.id===button.dataset.videoDelete);if(!await ctx.confirmAction('Video verwijderen',`De registratie van “${v.title}” wordt verwijderd. Kies Verbergen als de video niet meer op de site mag verschijnen.`)){feedback(ctx.root,'');return}value(await supabase.from('site_videos').delete().eq('id',v.id).eq('updated_at',v.updated_at).select('id').single());await renderVideos(ctx)}))
}

let feedCache
async function videoForm(ctx,id){
 const video=id?value(await supabase.from('site_videos').select('*').eq('id',id).single()):{},canEdit=may(ctx,id?'videos.edit':'videos.create'),publish=may(ctx,'videos.publish'),hide=may(ctx,'videos.hide')
 set(ctx.root,card(id?'Video bewerken':'Video toevoegen',`<a href="${href('videos')}">← Terug naar video’s</a><p class="admin-muted">Plak een YouTube-link. De afbeelding verschijnt automatisch; een bekende FVT-aflevering krijgt ook automatisch een titel.</p><form id="video-form" class="admin-form"><fieldset ${canEdit?'':'disabled'}>${input('YouTube-link','url',video.youtube_id?'https://www.youtube.com/watch?v='+video.youtube_id:'','type="url" required placeholder="https://www.youtube.com/watch?v=…"')}<p id="cms-video-lookup" role="status" aria-live="polite"></p><div id="cms-video-preview"></div>${input('Titel','title',video.title,'required minlength="3" maxlength="250" placeholder="Titel van de aflevering"')}<div class="admin-grid">${choose('Rubriek','category',VIDEO_CATEGORIES.map(c=>[c,c]),video.category||'Overige / Specials')}${input('Publicatiedatum','published_at',localDate(video.published_at||new Date().toISOString()),'type="datetime-local" required '+(publish?'':'disabled'))}${yesNo('Zichtbaar op de website','visible',video.visible,(video.visible?hide:publish)?'':'disabled')}${yesNo('Uitgelicht','featured',video.featured,publish?'':'disabled')}</div><label>Beschrijving (optioneel)<textarea name="description" maxlength="5000" rows="3">${esc(video.description)}</textarea></label><details class="cms-advanced"><summary>Geavanceerd</summary>${input('Eigen thumbnail (optioneel)','thumbnail_url',video.thumbnail_url,'type="url" pattern="https://.*"')}${input('Volgorde','sort_order',video.sort_order||0,'type="number" min="-10000" max="10000"')}</details></fieldset><div class="cms-form-actions">${canEdit?'<button type="submit" id="video-save" class="admin-primary">Video opslaan</button>':''}<a href="${href('videos')}">Annuleren</a></div>${notice}</form>`))
 const form=ctx.root.querySelector('#video-form');let ticket=0,titleChanged=!!id,categoryChanged=!!id,dateChanged=!!id,saving=false
 form.elements.fvt_title.addEventListener('input',()=>titleChanged=true);form.elements.category.onchange=()=>categoryChanged=true;form.elements.published_at.onchange=()=>dateChanged=true
 const showThumbnail=()=>{const youtube=ctx.youtubeId(form.elements.url.value);set(ctx.root.querySelector('#cms-video-preview'),youtube?`<img class="cms-video-preview" src="${esc(form.elements.thumbnail_url.value||thumbnailSources(youtube)[1])}" alt="Voorbeeld videothumbnail">`:'')};showThumbnail();form.elements.thumbnail_url.oninput=showThumbnail
 form.elements.url.onchange=async()=>{
  const current=++ticket,youtube=ctx.youtubeId(form.elements.url.value),message=ctx.root.querySelector('#cms-video-lookup');showThumbnail()
  if(!youtube){message.textContent='Plak een geldige YouTube-link.';return}message.textContent='Aflevering opzoeken…'
  try{if(!feedCache)feedCache=fetchVideoFeed().catch(error=>{feedCache=null;throw error});const feed=await feedCache;if(current!==ticket)return;const match=feed.videos?.find(v=>v.id===youtube);if(match){if(!titleChanged)form.elements.fvt_title.value=match.title;if(!categoryChanged)form.elements.category.value=videoCategory(match);if(!dateChanged)form.elements.published_at.value=localDate(match.published);message.textContent='Aflevering gevonden. Controleer de titel, rubriek en zichtbaarheid.'}else message.textContent='Afbeelding gevonden. Vul zelf de titel in; deze aflevering staat niet in de recente FVT-feed.'}catch{if(current===ticket)message.textContent='Afbeelding gevonden. De titel kon niet worden opgehaald; vul deze zelf in.'}
 }
 form.onsubmit=async event=>{event.preventDefault();if(!canEdit||saving)return;saving=true;try{await task(ctx.root,event.submitter||form.querySelector('[type=submit]'),async()=>{const youtube_id=ctx.youtubeId(form.elements.url.value);if(!youtube_id)throw Error('Gebruik een geldige YouTube-link.');const payload={youtube_id,title:form.elements.fvt_title.value,category:form.elements.category.value,description:form.elements.description.value,thumbnail_url:form.elements.thumbnail_url.value||thumbnailSources(youtube_id)[1],sort_order:Number(form.elements.sort_order.value)};if(publish)payload.published_at=new Date(form.elements.published_at.value).toISOString();if((video.visible?hide:publish))payload.visible=form.elements.visible.checked;if(publish)payload.featured=form.elements.featured.checked;value(await(id?supabase.from('site_videos').update(payload).eq('id',id).eq('updated_at',video.updated_at):supabase.from('site_videos').insert(payload)).select('id').single());location.assign(href('videos'))})}finally{saving=false}}
}
